services:
  api:
    image: ghcr.io/qianfuv/paper-scanner-api:latest
    expose:
      - "8000"
    volumes:
      - ./data:/app/data
    environment:
      - API_HOST=0.0.0.0

  app:
    image: ghcr.io/qianfuv/paper-scanner-app:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config:ro
    environment:
      - HOSTNAME=0.0.0.0
    depends_on:
      - api
